version: 2

jobs:

  android-test:
    working_directory: ~/cpal
    docker:     
      - 
        environment: 
          ANDROID_PLATFORM: android-18
        image: tomaka/cargo-apk
    steps:
      - run: rustup self update
      - run: rustup default stable
      - run: rustup target add armv7-linux-androideabi
      - run: rustup update
      - run: rustc --version
      - run: apt-get -qq update
      - run: apt-get install python-software-properties software-properties-common -y --fix-missing
      - run: sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
      - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: apt-get -qq update && apt-get install -y git
      - run: apt-get install -y clang-6.0
      - checkout
      - restore_cache:
          key: android-test-cache-{{ checksum "Cargo.toml" }}
      - run: "git clone https://github.com/tomaka/android-rs-glue.git && cd android-rs-glue && git reset --hard 8ad069e3bcad7523b95ed12946725f4bbbb2572e && cargo install --path cargo-apk --force"
      - run: cargo apk build
      - run: "ls target/android-artifacts/app/build/outputs/apk"
      - run: "pwd"
      #- run: "jarsigner -verbose -sigalg SHA1withRSA -storepass ${KEYPHRASE} -digestalg SHA1 -keystore my-release-key.keystore ${HOME}/project/target/android-artifacts/app/build/outputs/apk/app-release-unsigned.apk rustropy"
      #- run: "zipalign -f 4 ${HOME}/project/target/android-artifacts/app/build/outputs/apk/app-release-unsigned.apk ${HOME}/project/target/android-artifacts/app/build/outputs/apk/outfile.apk"
      - run: "chmod +x .circleci/upload_github_release.sh"
      - 
        run: 
          command: "./.circleci/upload_github_release.sh"
          name: "Deploy to Github"
      - save_cache:
          key: android-test-cache-{{ checksum "Cargo.toml" }}
          paths:
            - target  
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - android-test
