version: 2

jobs:

  android-test:
    working_directory: ~/cpal
    docker:
      - image: tomaka/cargo-apk
    steps:
      - run: apt-get -qq update
      - run: apt-get install python-software-properties software-properties-common -y --fix-missing
      - run: sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main"
      - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      - run: apt-get -qq update && apt-get install -y git
      - run: apt-get install -y clang-6.0
      - checkout
      - restore_cache:
          key: android-test-cache-{{ checksum "Cargo.toml" }}
      - run: cargo apk build --example opens
      - save_cache:
          key: android-test-cache-{{ checksum "Cargo.toml" }}
          paths:
            - target  
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - android-test
